name: .NET Framework 4.8 Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore dependencies
      run: nuget restore Daw.DB.sln

    - name: Build in Release Mode
      run: msbuild Daw.DB.sln /p:Configuration=Release

    - name: Run unit tests
      run: |
        cd Daw.DB.Tests/bin/Release/
        & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe' *.dll
